{% set version = "4.8.0" %}

package:
  name: nco
  version: {{ version }}

source:
  url: https://github.com/nco/nco/archive/{{ version }}.tar.gz
  sha256: 91f95ebfc9baa888adaec3016ca18a6297e2881b1429d74543a27fdfbe15fcab

build:
  number: 2
  skip: True  # [win and vc<14]

requirements:
  build:
    - cmake  # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libblas
    - libcblas
    - antlr >=2.7.7,<3
    - bison  # [not win]
    - texinfo  # [not win]
    - flex  # [not win]
    - m4  # [not win]
    - curl
    - expat
    - gsl
    - hdf5
    - krb5  # [not win]
    - libnetcdf  # [not win]
    - libnetcdf 4.6.1  # [win]
    - udunits2
    - zlib
  run:
    - curl
    - esmf  # [not win]
    - expat
    - gsl
    - hdf5
    - krb5  # [not win]
    - libnetcdf  # [not win]
    - libnetcdf 4.6.1  # [win]
    - udunits2
    - tempest-remap  # [not win]

test:
  source_files:
    - data/in.cdl
  commands:
    - ncks --help
    - ncap2 --help
    - ncks -M "http://tds.marine.rutgers.edu/thredds/dodsC/roms/espresso/2013_da/his/ESPRESSO_Real-Time_v2_History_Best"

about:
  home: http://nco.sourceforge.net/
  license: GPL-3.0
  summary: 'Suite of programs for manipulating NetCDF/HDF4 files.'

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
    - xylar
