{% set version = "4.7.0" %}

package:
  name: nco
  version: {{ version }}

source:
  url: https://github.com/nco/nco/archive/{{ version }}.tar.gz
  sha256: 5ba930f00a0e9775f85748d145acecfe142f917c180de538b2f8994788446cf8

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - gsl >=2.2,<2.3
    - antlr
    - curl >=7.44.0,<8
    - zlib 1.2.11
    - hdf5 1.8.18|1.8.18.*
    - hdf5 1.10.1
    - libnetcdf 4.4.*
    - udunits2
    - expat 2.1.*
    - krb5 1.14.*
    - texinfo
    - bison
    - flex
    - m4
  run:
    - gsl >=2.2,<2.3
    - hdf5 1.8.18|1.8.18.*
    - hdf5 1.10.1
    - libnetcdf 4.4.*
    - udunits2
    - expat 2.1.*
    - libgcc
    - esmf
    - openblas 0.2.19|0.2.19.*

test:
  source_files:
    - data/in.nc
  commands:
    - ncks --help
    - ncap2 --help
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://nco.sourceforge.net/
  license: GPL-3.0
  summary: 'Suite of programs for manipulating NetCDF/HDF4 files.'

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
    - xylar
