{% set version = "4.6.4" %}

package:
  name: nco
  version: {{ version }}

source:
  fn: nco-{{ version }}.tar.gz
  url: https://github.com/nco/nco/archive/{{ version }}.tar.gz
  sha256: 1c2ab906fc81f91bf8aff3e6da27ae7a4c89821c5836d787188fff5262418062
  patches:
    - no_szip.patch  # [win]
    - nco_fl_utl_C2055.patch  # [win]

build:
  number: 0
  skip: True  # [py>35]
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py>=35]

requirements:
  build:
    - python  # [win]
    - cmake  # [win]
    - gsl  # [not win]
    - antlr  # [not win]
    - curl
    - zlib 1.2.*
    - hdf5 1.8.17|1.8.17.*
    - libnetcdf 4.4.*
    - udunits2
    - expat
    - krb5
    - texinfo  # [not win]
    - bison  # [not win]
    - flex 2.6.0  # [not win]
    - m4  # [not win]
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]
  run:
    - gsl  # [not win]
    - hdf5 1.8.17|1.8.17.*
    - libnetcdf 4.4.*
    - udunits2
    - expat
    - libgcc  # [not win]
    - esmf  # [not win]
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]

test:
  source_files:
    - data/in.nc
  commands:
    - ncks --help
    - ncap2 --help  # [not win]
    - conda inspect linkages -p $PREFIX nco  # [not win]
    - conda inspect objects -p $PREFIX nco  # [osx]

about:
  home: http://nco.sourceforge.net/
  license: GPL-3.0
  summary: 'Suite of programs for manipulating NetCDF/HDF4 files.'

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
