{% set version = "5.0.5beta02" %}
{% set build = 0 %}

package:
  name: nco
  version: {{ version }}

source:
  url: https://github.com/nco/nco/archive/5.0.5-beta02.tar.gz
  sha256: aec681cf99ada2b61bff1ce5158ca64d2422005eda4899264b98aeda85e8c38a

build:
  number: {{ build }}
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake  # [win]
    - make  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - libblas
    - libcblas
    - antlr >=2.7.7,<3
    - bison  # [not win]
    - texinfo  # [not win]
    - flex  # [not win]
    - m4  # [not win]
    - curl
    - expat
    - gsl
    - krb5  # [not win]
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - udunits2
    - zlib
    # need to list these twice to get version pinning from conda_build_config
    # and nompi build pinning
    - hdf5
    - hdf5 * nompi_*
    - libnetcdf
    - libnetcdf * nompi_*
  run:
    - curl
    - esmf  # [not win]
    - expat
    - gsl
    - hdf5
    - krb5  # [not win]
    - libnetcdf
    - udunits2
    - tempest-remap  # [not win]

test:
  source_files:
    - data/in.cdl
  commands:
    - ncks --help
    - ncap2 --help
    - ncks -M "http://tds.marine.rutgers.edu/thredds/dodsC/roms/espresso/2013_da/his/ESPRESSO_Real-Time_v2_History_Best"

about:
  home: http://nco.sourceforge.net/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: Suite of programs for manipulating NetCDF/HDF4 files

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
    - xylar
