{% set version = "4.7.0" %}

package:
  name: nco
  version: {{ version }}

source:
  url: https://github.com/nco/nco/archive/{{ version }}-alpha04.tar.gz
  sha256: 12018b57d3506043770567de8cf9758187092038c265f14a0187b5951efb5e41

build:
  number: 0
  skip: True  # [win and py<=35]
  skip: True  # [win32]
  features:
    - vc14  # [win and (py35 or py36)]

requirements:
  build:
    - python  # [win]
    - cmake  # [win]
    - antlr  # [not win]
    - bison  # [not win]
    - texinfo  # [not win]
    - flex  # [not win]
    - m4  # [not win]
    - curl >=7.44.0,<8
    - expat 2.1.*
    - gsl >=2.2,<2.3  # [not win]
    - hdf5 1.8.18|1.8.18.*
    - krb5 1.14.*  # [not win]
    - libnetcdf 4.4.*
    - udunits2
    - zlib 1.2.11
    - vc 14  # [win and (py35 or py36)]
  run:
    - curl >=7.44.0,<8
    - expat 2.1.*
    - gsl >=2.2,<2.3  # [not win]
    - hdf5 1.8.18|1.8.18.*
    - krb5 1.14.*  # [not win]
    - libnetcdf 4.4.*
    - udunits2
    - libgcc  # [not win]
    - openblas 0.2.19|0.2.19.*  # [not win]
    - esmf  # [not win]
    - vc 14  # [win and (py35 or py36)]

test:
  source_files:
    - data/in.nc
  commands:
    - ncks --help
    - ncap2 --help  # [not win]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://nco.sourceforge.net/
  license: GPL-3.0
  summary: 'Suite of programs for manipulating NetCDF/HDF4 files.'

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
    - xylar
