travis:
  secure:
    BINSTAR_TOKEN: ZgykdmnvYn4+f2MRRuV5jOgdkVuCWaoksWEdibgdflcmWy0EY4Qt7CfAZSU7l4iUXZqyWfefUr1UE1DXt2r3dymZaKOjsNYe0d6OQK9hdf7vvJPASGawe5CW3s9vDhIAPXrLbTgkdlsZAyi3zZ2zjutFNj28z7US1Y8fBIVU8TutMZQepRWX2Iue7fIeEBUUg1iOSPf9kGGWawA5N/oCzvIlRxq6ff1SbiJ4XnfPUi4Ts+Kl2q+5ijJypKypLL33fky0RiM9SevEVnHAnG2CwApCy7GuDj5lKbDkNySwP/T4wmpvX23jNBNuT1YVOwnEBjzaRaJXiFHQYbZV37fME+5DZUYAVZc8XHl5cm9MJWzeJ7EU+51M8tF5dvg5LhJ4xlCS0Zj5GVKnlodwCbwfKJJ7qE/tSX0R/mzdWazDBW4HvDcm1+0Nr0bMJqAyhA3ElSOV7Mm09kchA+qFfeQlR6khKNFpUcX95/NY4Dq2ifSRBEdHlxNe082nVltxvLgbvQVn2bK40kfslzlcRb4jNWPPfiIbeUZCdzhOmdBtWGLrEpask03R/tlbRO+AKDYxE71S87YUDoyrDDTYLIAit8cJUtjnax7Fz5C6rpDlApH6i4PBZRG1k1bqTu8mRVxE6OlpWEDA2swUH60BnQLt/8rVNgNCl1pnAwcZvWAAG3I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
